[build.environment]
  NODE_VERSION = "14"
  NPM_VERSION = "9"

[build]
  command = "npm run --workspaces build"
  publish = "dist/"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
