[build.environment]
  NODE_VERSION = "14"

[build]
  command = "nmp build --worksites"
  publish = "dist/"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
